### ISSUE TITLE
h2 protocol error: protocol error: received frame when stream half-closed

### ISSUE THREAD

**Issue by pixelchrome** [helium/gateway-rs#47]
I've setup a Dragino LPS8 as a Light-GW. But I can not see that my device (Dragino LGT92) connects to helium properly.

Release v1.0.0-alpha.9

Warning message

```
daemon.info helium_gateway[xxxx]:  WARN ignoring uplink error: Service(Rpc(Status { code: Unknown, message: "h2 protocol error: protocol error: received frame when stream half-closed", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} } })), module: router
```

**Comment by pe1mew** [comment]
For what it is worth I have the same warning on a RAK7258 running Release v1.0.0-alpha.9

```
Mon May 17 12:36:57 2021 daemon.info helium_gateway[30916]:  WARN ignoring uplink error: Service(Rpc(Status { code: Unknown, message: "h2 protocol error: protocol error: received frame when stream half-closed", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} } })), module: router
```

**Comment by madninja** [comment]
@pixelchrome @pe1mew could you verify in your default.toml that the staging router is uncommented and equal to:

```
public_key = "11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv"
uri = "http://54.193.165.228:8080"
```

and confirm that a restart of the gateway does not fix it?

**Comment by pe1mew** [comment]
I can confirm that ```/etc/helium_gateway/default.toml``` contains: 
```
# staging
public_key = "11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv"
uri = "http://54.193.165.228:8080"
```
and a restart does not solve it.

**Comment by pixelchrome** [comment]
Same for me. I can confirm that `/etc/helium_gateway/default.toml` contains the mentioned values. And a restart does not solve it.

`/etc/helium_gateway/default.toml`

```toml
keypair = "/etc/helium_gateway/key.bin"
listen_addr = "127.0.0.1:1680"
region = "US915"

[log]
method = "stdio"
level = "info"
timestamp = false

[update]
# Enable update checking
enabled = true
# OVERRIDE: Platform to use as part of update check. This MUST be overriden by a
# local settings file
platform = "unknown"
# Channel to use, alpha, beta, release, or semver which pulls it from the
# running program
channel = "semver"
# Interval in minutes between update checks
interval = 10
# The github release stream to check for updates
uri = "https://api.github.com/repos/helium/gateway-rs/releases"
# The command to run to install the update.
command = "/etc/helium_gateway/install_update"

# A list of gateway service keys and urls (note https is not supported
[[gateways]]
# ohio2
public_key = "112AY1cJ9quokGVZL8uVQ9Jih1cHsji2VVoKApf2fVPBseHcRsgA"
uri = "http://18.216.219.228:8080"


## Default router
[router]
# dev
#public_key = "1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB"
#uri = "http://54.176.88.149:8080"
# staging
public_key = "11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv"
uri = "http://54.193.165.228:8080"
# production
#public_key = "112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE"
#uri = "http://52.8.80.146:8080"
```

`/etc/helium_gateway/settings.toml`

```toml
[log]
method = "stdio"
level = "info"
timestamp = false

[update]
platform = "dragino"

region = "EU868"
```
